apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
  labels: { app: hello-flask }
spec:
  replicas: 1
  selector:
    matchLabels: { app: hello-flask }
  template:
    metadata:
      labels: { app: hello-flask }
    spec:
      containers:
        - name: hello-flask
          image: hello-flask:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"