apiVersion: v1
kind: Service
metadata:
  name: hello-flask
  labels: { app: hello-flask }
spec:
  type: ClusterIP
  selector:
    app: hello-flask
  ports:
    - name: http
      port: 80
      targetPort: 8000